os: linux
dist: trusty

language: java
jdk:
  - oraclejdk8

script:
  - ./gradlew test

after_success:
  - ./gradlew jacocoTestReport
  - find . -name jacocoTestReport.csv | xargs cat| awk -F',' '{print $3" "$4" "$5}'